// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"share_word/internal/db"
)

func Dashboard(user *db.User, myPuzzles []db.GetPuzzlesByOwnerRow, followingPuzzles []db.GetPuzzlesFromFollowingWithUsernameRow) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container stack\" data-signals=\"{name: '', width: 15, height: 15}\"><div class=\"flex items-center justify-between\"><h1>My Dashboard</h1></div><section class=\"card stack\" style=\"background: var(--slate-100); border-style: dashed; border-width: 2px;\"><h2 class=\"text-lg font-bold\">Create a New Puzzle</h2><form class=\"flex gap-4 items-end\"><div class=\"form-group\" style=\"flex: 1;\"><label>Puzzle Name</label> <input name=\"name\" type=\"text\" class=\"input\" placeholder=\"e.g. Sunday Morning Fun\" data-bind:name></div><button type=\"button\" class=\"btn-primary\" style=\"height: 38px;\" data-on:click=\"@post('/puzzles')\">Create Puzzle</button></form></section><hr style=\"border: 0; border-top: 1px solid var(--slate-200); margin: var(--space-4) 0;\"><section class=\"stack\"><h2 class=\"text-lg font-bold\">My Puzzles</h2>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(myPuzzles) == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"card text-center text-slate-500\" style=\"background: transparent;\"><p>You haven't created any puzzles yet.</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = PuzzleList(myPuzzles).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(followingPuzzles) > 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<hr style=\"border: 0; border-top: 1px solid var(--slate-200); margin: var(--space-4) 0;\"><section class=\"stack\"><h2 class=\"text-lg font-bold\">Puzzles from Following</h2>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = PuzzleListFromFollowing(followingPuzzles).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
