// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Session struct {
	Token  string
	Data   []byte
	Expiry float64
}

type User struct {
	ID           string
	Username     string
	PasswordHash string
	CreatedAt    time.Time
}
